batch_size : 30
n_chunks : 1
train_size : 2000
sigma : 0.05
random_seed : null
multistart: false
n_eval: 1

trunc_chain_len: 2000
burn_in: 1000
n_steps: &n_steps 2000
every: &every 2000



device: cpu
figpath: figs/swissroll
respath: dump
data_root: data

methods:
  ULA:
    mcmc_class: ULA
    params:
      grad_step: 0.0001
      noise_scale: 0.0002
      #noise_scale: 0.045
    n_steps : *n_steps
    every: *every
    burn_in: *n_steps
    #every : 200
    color : "tab:brown"

  ULA_1:
    mcmc_class: ULA
    params:
      grad_step: 0.001
      noise_scale: 0.002
      #noise_scale: 0.045
    n_steps : *n_steps
    every: *every
    burn_in: *n_steps
    #every : 200
    color : "tab:brown"

  MALA:
    mcmc_class: MALA
    params:
      grad_step: 0.001
      adapt_stepsize: True
    n_steps : *n_steps
    every: *every
    burn_in: *n_steps
    color : "tab:green"

  # CISIR:
  #   mcmc_class: CISIR
  #   params:
  #     N: 10
  #     corr_coef: 0.9
  #     bernoulli_prob_corr: 0.5
  #   n_steps : *n_steps
  #   every: *every
  #   burn_in: *n_steps
  #   color : "tab:orange"

  "Ex$^2$MCMC":
    mcmc_class: Ex2MCMC
    params:
      N: 10
      grad_step: 0.001
      adapt_stepsize: True
      corr_coef: 0.9
      bernoulli_prob_corr: 0.5
      mala_steps: 1
    n_steps : *n_steps
    every: *every
    burn_in: *n_steps
    color : "tab:red"

  # "Ex$^2$MCMC w/o corr":
  #   mcmc_class: Ex2MCMC
  #   params:
  #     N: 10
  #     grad_step: 0.01
  #     adapt_stepsize: True
  #     # corr_coef: 0.9
  #     # bernoulli_prob_corr: 0.5
  #     mala_steps: 1
  #   n_steps : 1000
  #   every : 200
  #   color : "tab:purple"

  # FlEx$^2$MCMC:
  #   mcmc_class: Ex2MCMC
  #   params:
  #     N: 10
  #     grad_step: 0.01
  #     adapt_stepsize: True
  #     corr_coef: 0.9
  #     bernoulli_prob_corr: 0.5
  #     mala_steps: 1
  #   n_steps: 1000
  #   every: 200
  #   flow:
  #     num_flows: 4
  #     lr: 0.01
  #     batch_size: 100
  #     n_steps: 200
  #   color: "tab:pink"
