device: cpu
figpath: figs
respath: dump/phi_four
data_root: data

trunc_chain_len: 2500
batch_size: 100

# 'tab:blue'
# 'tab:orange'
# 'tab:green'
# 'tab:red'
# 'tab:purple'
# 'tab:brown'
# 'tab:pink'
# 'tab:gray'
# 'tab:olive'
# 'tab:cyan'

N: 100
dim_phys: 1
prior_type: coupled
prior_a: 1
a_coupling: 0.1
b_field: 0
beta: 20.0
tilt_value: null
tilt_lambda: null
depth_blocks: 2
hidden_dim: 50
ratio_pos_init: 0.5 #-1

methods:
  # MALA:
  #   mcmc_class: MALA
  #   n_steps: 1000
  #   # ess_rar: 50
  #   params:
  #     grad_step:
  #     adapt_stepsize: True

  # "Ex$^2$MCMC w/o corr":
  #   mcmc_class: Ex2MCMC
  #   n_steps: 1000
  #   # ess_rar: 1
  #   params:
  #     N: 10
  #     grad_step: 0.01
  #     adapt_stepsize: True
  #     mala_steps: 1

  # "Ex$^2$MCMC w corr":
  #   mcmc_class: Ex2MCMC
  #   n_steps: 1000
  #   # ess_rar: 1
  #   params:
  #     N: 10
  #     grad_step: 0.01
  #     adapt_stepsize: True
  #     corr_coef: 0.9
  #     bernoulli_prob_corr: 0.5
  #     mala_steps: 1

  "FlEx$^2$MCMC":
    mcmc_class: Ex2MCMC
    short_name: flex_N_10_corr
    # ess_rar: 1
    params:
      N: 10
      #grad_step: 0.001 #0.01
      #adapt_stepsize: True
      grad_step: 0.0001
      corr_coef: 0.9
      bernoulli_prob_corr: 0.5
      mala_steps: 10
    flow:
      lr: 0.001
      n_steps: 10000
      burn_in_steps: 1000
      start_optim: 0 #1000
    color: 'tab:pink'

  # "FlEx$^2$MCMC, w/o corr":
  #   mcmc_class: Ex2MCMC
  #   short_name: flex_N_10
  #   # ess_rar: 1
  #   params:
  #     N: 10
  #     #grad_step: 0.001
  #     #adapt_stepsize: True
  #     grad_step: 0.0001
  #     mala_steps: 10
  #   flow:
  #     lr: 0.001
  #     n_steps: 10000
  #     burn_in_steps: 1000
  #     start_optim: 0 #1000
  #   color: 'tab:olive'

  "Augmented MALA":
    mcmc_class: Ex2MCMC
    short_name: ex_N_2
    # ess_rar: 1
    params:
      N: 2
      #grad_step: 0.001
      #adapt_stepsize: True
      grad_step: 0.0001
      mala_steps: 10
    flow:
      lr: 0.001
      n_steps: 10000
      burn_in_steps: 1000
      start_optim: 0 #1000
    color: 'tab:gray'



  # "AugmentedULA":
  #   mcmc_class: AugmentedULA
  #   # ess_rar: 1
  #   params:
  #     #grad_step: 0.001 #0.01
  #     #adapt_stepsize: True
  #     grad_step: 0.0001 #0.01
  #     mala_steps: 10 #0
  #     n_steps: 1
  #   flow:
  #     lr: 0.001 #0.001
  #     batch_size: 100
  #     n_steps: 1000 #4000 #1000 #1000 #000
  #     burn_in_steps: 1000 #10 #1000 #1000
  #     start_optim: 0 #1000

  # "AugmentedMALA w corr":
  #   mcmc_class: Ex2MCMC
  #   # ess_rar: 1
  #   params:
  #     grad_step: 0.001 #0.01
  #     adapt_stepsize: True
  #     #grad_step: 0.0005 #0.01
  #     mala_steps: 1 #0
  #     n_steps: 1
  #     corr_coef: 0.9 #0.9
  #     bernoulli_prob_corr: 0.5 #0.5
  #   flow:
  #     num_flows: 4
  #     lr: 0.001 #0.001
  #     batch_size: 100
  #     n_steps: 3000 #4000 #1000 #1000 #000
  #     #burn_in_steps: 0 #10 #1000 #1000
  #     start_optim: 0 #1000
